all tasks
Jampire/php-andrei-zhartun pull request #2
Opened 2022-05-03 18:08 UTC by andreyzh777

2022-05-11 21:54 UTC, Jampire requested changes

2022-05-11 21:54 UTC, Jampire commented on src/Task12/task12.php
> +    while ((int) $time->format('j') != 1) {
Use strong comparison.

2022-05-11 21:54 UTC, Jampire commented on src/Task12/task12.php
> +        if ((int) $time->format('w') == 1) {
Use strong comparison.

2022-05-11 21:54 UTC, Jampire commented on src/Task12/task12.php
> +            array_push($result, (string)$time->format("d.m.Y"));
Use `$result[] = (string)$time->format("d.m.Y")` to add single element to the list.

2022-05-11 21:54 UTC, Jampire commented on src/Task12/task12.php
> +foreach ($arr as $data) {
Use `implode()` to print array.

2022-05-11 21:54 UTC, Jampire commented on src/Task13/task13.php
> +function delArray(array $a, int $elem): array
Wrong function name. Are you trying to delete whole array?
Wrong second argument name. It's not an element, but position number.

2022-05-11 21:54 UTC, Jampire commented on src/Task14/task14.php
> +<?php
OK, but can be done with one `array_flip()`.

2022-05-11 21:54 UTC, Jampire commented on src/Task15/task15.php
> +    $kolElementA = count($a);
English names only.

2022-05-11 21:54 UTC, Jampire commented on src/Task15/task15.php
> +*/
Wrong output.
Input:
```
[3,6,7,8,10]
```
Expected:
```
[
    [1] => 4
    [2] => 5
    [6] => 9
]
```
Actual:
```
[
    [3] => 4
    [4] => 5
    [8] => 9
]
```

2022-05-11 21:54 UTC, Jampire commented on src/Task18/task18.php
> +        return false;
What will you do, if `false` is actual array value?

2022-05-11 21:54 UTC, Jampire commented on src/Task18/task18.php
> +if ($element !== false) {
Move this calculation into the function.

2022-05-13 13:13 UTC, andreyzh777 commented on src/Task15/task15.php
> +*/
it is not entirely clear how the conclusion is formed
what should be the output if?
Input:
[3,7,9,10]

2022-05-13 20:14 UTC, andreyzh777 commented on src/Task18/task18.php
> +        return false;
false or true kill work script.
Script working with array string, int, double.

2022-05-18 18:00 UTC, Jampire commented on src/Task18/MyFunction.php
> +    return $nameElement ? $nameElement : 'false';
And if `'false'` is actual majority element?

2022-05-18 19:53 UTC, merged